server:
  port: ${PORT:8081}

spring:
  datasource:
    platform: postgres
    url: ${DB_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql.sql
